#!/usr/bin/env node

'use strict';

var join = require('path').join
var spawn = require('child_process').spawn
var Readable = require('stream').Readable

let args = [join(__dirname,'runner.js')].concat(process.argv.slice(2))
let proc = spawn('./node_modules/.bin/electron', args, { stdio: 'inherit'})

/*
let reader = new Readable()
reader._read = function(){}
reader.pipe(faucet()).pipe(process.stdout)
proc.stdout.on('data',(data)=>{
    reader.push(data.toString())
})
*/
proc.on('close',(code)=>{
    process.exit(code)
})
